[versions]
minecraft = "1.21.11"

# https://fabricmc.net/develop/
fabricLoader = "0.18.4"
fabricApi = "0.140.2+1.21.11"
fabricLoom = "1.14-SNAPSHOT"
yarn_mappings = "1.21.11+build.3"

pl3xmap = "1.21.11-SNAPSHOT"
openPartiesAndClaims = "6859742"

paper = "1.21.11-R0.1-SNAPSHOT"

shadow = "9.3.0"
minotaur="2.+" # https://github.com/modrinth/minotaur
run-paper="3.0.2" # https://github.com/jpenilla/run-task

gson="2.13.2" # https://github.com/google/gson
owasp_java_html_sanitizer = "20240325.1"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
fabric-loom = { id = "fabric-loom", version.ref = "fabricLoom" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
yarn-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "yarn_mappings" }

paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

openPartiesAndClaims = { group = "curse.maven", name = "open-parties-and-claims-636608", version.ref = "openPartiesAndClaims" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
owaspJavaHtmlSanitizer = { group = "com.googlecode.owasp-java-html-sanitizer", name = "owasp-java-html-sanitizer", version.ref = "owasp_java_html_sanitizer" }

pl3xmap = { group = "maven.modrinth", name = "pl3xmap", version.ref = "pl3xmap" }